### ISSUE TITLE
introduction.md中的cdn链接还是vue2的

### ISSUE THREAD

**Issue by huzhengen** [ShenQingchuan/docs-next#6]
我找到的vue3的链接：https://cdn.jsdelivr.net/npm/vue@3.0.0-rc.7/dist/

**Comment by ShenQingchuan** [comment]
回复：您好，感谢 issue
您提出的问题很有价值，在 v3.vuejs.org 中这部分引入 CDN 的内容并未存在，关于如何引入 Vue 资源的相关指引都已经收敛到了 `installation.md` 当中。
而且一个 rc 阶段的 cdn 之后还会有频繁的变动，文档可能也需要反复更新，没有必要，所以我们打算暂时移除这部分翻译。
